disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "beatz by emme."

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "emmelogo.png"

[params.author]
bio = "i create music. beats. sounds. things that you want to hear. and i do it for myself, but you're welcome to join me on the ride."
